name: lighthouse audit

on:
  pull_request:
    branches:
      - master

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.sha}}
      - uses: actions/setup-node@v1

      - name: npm install
        run: npm install && npm install -g @lhci/cli

      - name: build
        run: npm run build

      - name: Lighthouse audit CI
        run: lhci autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
